In [1]:
import numpy as np

Acceso a datos de matriz de dos dimensiones

In [71]:
#Matriz de n filas y m columnas
mtx = np.zeros([5,5],dtype=float)

print("tamaño:",mtx.shape)
print("cantidad de dimensiones:",mtx.ndim)
print("lingitud total:",mtx.size)
print("tipo de dato:",mtx.dtype)
#print(mtx)
print("-----------------------------------")
print(mtx[0])
print("-----------------------------------")
print(mtx[0:3,0:2]) # [Filas , columns]

tamaño: (5, 5)
cantidad de dimensiones: 2
lingitud total: 25
tipo de dato: float64
-----------------------------------
[0. 0. 0. 0. 0.]
-----------------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]


Creando y manipulando una matriz de 3 dimensiones

In [102]:
#Matriz de:
#d dimensiones
#n filas
#m columnas

mtx = np.zeros([2,3,3],dtype=float)

print("tamaño:",mtx.shape)
print("nro de orden (define el nD tensor):",mtx.ndim)
print("lingitud total:",mtx.size)
print("tipo de dato:",mtx.dtype)
#print(mtx)
print("-----------------------------------")
print(mtx[0]) #-->Accedemos a la primera dimension
print("-----------------------------------")
print(mtx[0,0:2]) #--> Dim. 1 , filas de 0 a 2.
print("-----------------------------------")
print(mtx[:,0,...]) #--> Todas las Dim. elemento 0, todas las columnas
print("-----------------------------------")
print(mtx[...,0]) #--> Todas las Dim. elemento 0

tamaño: (2, 3, 3)
nro de orden (define el nD tensor): 3
lingitud total: 18
tipo de dato: float64
-----------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
-----------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
-----------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
